version: "3.8"
services:
  posting:
  build:
  context: ./PostingService
  dockerfile: Dockerfile
  restart: always
  ports:
  - 80:5000
  networks:
  - internal
  environment:
  CONNECTION_STRING: Host=posting-db;User=root;Password=root;Port=5432
  db:
    image: postgres
      #volumes:
      #- db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: jp2gmd
      POSTGRES_DB: mlm
volumes:
  db-data:
